### ISSUE TITLE
myBloomington

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/myBloomington#13]
**`Overview`** story ticket for the **`myBloomington`** JS rewrite.

### In-Progress
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/47 :: **`2020 City Council`** **[BLOCKED]** - **`bios/images`** (Kate Rosenbarger, Ron Smith, Matt Flaherty)

### Backlog
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/26 :: **`Accessibility`**
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/43 :: **`go back home`**
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/17 :: **`SEO`** optimization
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/19 :: graceful/useful **`Erroring`** per component/section
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/23 :: potentially **`Street View`** the address if applicable
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/29 :: **`Testing`** for desired consistency 
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/24 :: port applicable **`Component`** updates back to Design System

### Backlog - Blocked
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/32 :: **`City Council photos`** (updated headshots - January)
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/31 :: **`Master Address - incomplete address data`** (awaiting Laura to check comment)
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/25 :: **`Sanitation`** - (awaiting for pickup date sync method (Laura via Rhea))
- [ ] https://github.com/City-of-Bloomington/myBloomington/issues/33 :: **`Master Address - Address Results`** (need more than 20)
